# -*- coding: utf-8 -*-

"""
/***************************************************************************
 EcosystemServiceValuator
                                 A QGIS plugin
 Calculate ecosystem service values for a given area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-04-02
        copyright            : (C) 2018 by Phil Ribbens/Key-Log Economics
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Phil Ribbens/Key-Log Economics'
__date__ = '2018-04-02'
__copyright__ = '(C) 2018 by Phil Ribbens/Key-Log Economics'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import numpy as np
from numpy import copy
import processing

from os.path import splitext

from PyQt5.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFeatureSink,
                       QgsFields,
                       QgsField,
                       QgsFeature,
                       QgsFeatureSink,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterFileDestination
                       )

from .parser import HTMLTableParser


class RasterLayerUniqueValuesReportTableAlgorithm(QgsProcessingAlgorithm):
    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.
    INPUT_RASTER = 'INPUT_RASTER'
    HTML_OUTPUT_PATH = 'HTML_OUTPUT_PATH'
    OUTPUT_TABLE = 'OUTPUT_TABLE'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm
        """

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_RASTER,
                self.tr('Input raster')
            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.HTML_OUTPUT_PATH,
                self.tr('Place to save intermediate html file')
            )
        )

        # Add a feature sink for the output data table
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_TABLE,
                self.tr('Output table of raster unique values')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        log = feedback.setProgressText
        input_raster = self.parameterAsRasterLayer(parameters, self.INPUT_RASTER, context)
        html_output_path = self.parameterAsFileOutput(parameters, self.HTML_OUTPUT_PATH, context)

        processing.run("native:rasterlayeruniquevaluesreport", {'INPUT':input_raster, 'BAND': 1, 'OUTPUT_HTML_FILE': html_output_path}, feedback=feedback)

        input_html = open(html_output_path, 'r', encoding='latin1')
        input_html_string = input_html.read()

        output_table_fields = QgsFields()
        output_table_fields.append(QgsField("value"))
        output_table_fields.append(QgsField("pixel_count"))
        output_table_fields.append(QgsField("area_m2"))

        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT_TABLE,
                context,
                output_table_fields)

        result = {self.OUTPUT_TABLE : dest_id}

        # instantiate the parser and then parse the table elements into a python list of lists
        # (per https://stackoverflow.com/questions/6325216/parse-html-table-to-python-list/22320207#22320207)
        p = HTMLTableParser()
        p.feed(input_html_string)
        table_as_list_of_lists = p.tables[0]
        # delete the header row
        del table_as_list_of_lists[0]

        #iterate through the list adding a new feature to the feature sink for every row
        # and a new attribute for every data point
        for tr in table_as_list_of_lists:
            new_feature = QgsFeature(output_table_fields)
            for counter, td in enumerate(tr):
                new_feature.setAttribute(counter, td)
            # Add a feature in the sink
            sink.addFeature(new_feature, QgsFeatureSink.FastInsert)

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return result

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Raster layer unique values report (table)'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Ecosystem service valuator'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return RasterLayerUniqueValuesReportTableAlgorithm()
