# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EcoValuator
                                 A QGIS plugin
 Calculate ecosystem service values for a given area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-04-02
        copyright            : (C) 2018 by Key-Log Economics
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Key-Log Economics'
__date__ = '2018-04-02'
__copyright__ = '(C) 2018 by Key-Log Economics'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EcoValuator class from file eco_valuator.py

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .eco_valuator import EcoValuatorPlugin
    return EcoValuatorPlugin()
